[package]
name = "rust_gym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
egui = "0.19.0"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand_isaac = "0.3.0"
serde = "1.0.148"
